variables:
  minio_host: $minio_host
  minio_username: $minio_username
  minio_password: $minio_password
  minio_bucket: $minio_bucket

stages:
  - build
 
build-job:
  stage: build
  image: node:16
  script:
    - apt update && apt install python3-pip -y && pip3 install sde
    - VERSION=$(git rev-parse --short HEAD)
    - sde VERSION $VERSION src/config.json
    - yarn install
    - yarn build 
    - tar -czvf ui.tar.gz dist/
    - bash ./upload_to_minio.sh $minio_host $minio_username $minio_password $minio_bucket / ui.tar.gz
  artifacts:
    paths:
      - ui.tar.gz
    expire_in: 1 day


